---
# mount any drives you find
- name: Mount hard drives
  hosts: pi
  become: true
  # gather_facts: true
  vars_files:
    - ../vars/vars.yml

  tasks:
  - name: create mount folders
    file:
      path: "{{ item.value.path }}"
      state: directory
    loop: "{{ lookup('dict', mount_by_labels) }}"

  - name: Mount hard drives
    ansible.posix.mount:
      path: "{{ item.value.path }}"
      src: "LABEL={{ item.value.label }}"
      fstype: "{{ item.value.fstype }}"
      state: mounted
    loop: "{{ lookup('dict', mount_by_labels) }}"

  ## Start installing MergerFS
  - name: Clone latest version (2.32.6)
    git:
      repo: https://github.com/trapexit/mergerfs.git
      dest: /src/mergerfs
      version: 2.32.6

  - name: install mergerfs
    shell: sudo make -C /src/mergerfs/ install
    register: make
    become: true
    # when <mergerfs -v doesnt return 2.32.6>

  - debug: var=make.stdout_lines

  # using  this link https://zackreed.me/mergerfs-another-good-option-to-pool-your-snapraid-disks/
  # /mnt/data/* /storage fuse.mergerfs allow_other,direct_io,use_ino,category.create=lfs,moveonenospc=true,minfreespace=20G,fsname=mergerfsPool 0 0
