---
# mount any drives you find
- name: Mount hard drives
  hosts: pi
  become: true
  # gather_facts: true
  vars_files:
    - ../vars/vars.yml

  tasks:
  - name: create mount folders
    file:
      path: "{{ item.value.path }}"
      state: directory
    loop: "{{ lookup('dict', mount_by_labels) }}"

  - name: Mount hard drives
    ansible.posix.mount:
      path: "{{ item.value.path }}"
      src: "LABEL={{ item.value.label }}"
      fstype: "{{ item.value.fstype }}"
      state: mounted
    loop: "{{ lookup('dict', mount_by_labels) }}"

  ## Start installing MergerFS
  - name: Clone latest version (2.32.6)
    git:
      repo: https://github.com/trapexit/mergerfs.git
      dest: /src/mergerfs
      version: 2.32.6

  - name: install mergerfs
    shell: sudo make -C /src/mergerfs/ install
    register: make_mergerfs
    become: true
    # when <mergerfs -v doesnt return 2.32.6>

  - debug: var=make_mergerfs.stdout_lines

  - name: Mount mergerfs
    ansible.posix.mount:
      path: "{{ mergerfs_mounts.path}}"
      src: "{{ mergerfs_mounts.src }}"
      fstype: "{{ mergerfs_mounts.fstype }}"
      opts: "{{ mergerfs_mounts.opts }}"
      state: mounted
    # loop: "{{ query('dict', mergerfs_mounts) }}"


  ## Start installing Snapraid
  - name: Clone latest version (v11.5)
    git:
      repo: https://github.com/amadvance/snapraid.git
      dest: /src/snapraid
      version: v11.5

  # Not sure if all of these are needed
  - name: Install dependencies (to build) snapraid
    apt:
      pkg:
        - autoconf
        - automake
        - libtool
    become: true

  # there was a make check, which I am skipping.
  - name: install snapraid
    shell:
      cmd: |
        sudo ./autogen.sh
        sudo ./configure
        sudo make
        sudo make install
      chdir: /src/snapraid/
    register: make_snapraid
    become: true
    # when <snapraid -v doesnt return 11.5>

  - debug: var=make_snapraid.stdout_lines

  ## Configure snapraid
  - name: Create snapraid configuration file
    copy:
      src: "../files/snapraid.conf"
      dest: "/etc/snapraid.conf"
    become: true
