---
# mount any drives you find
- name: Set up samba
  hosts: pi
  become: true
  # gather_facts: true
  vars_files:
    - ../vars/samba_vars.yml
  pre_tasks:

  - name: Create system level users & prevent non-root users from login into the system using nologin shell
    user:
      name: "{{ item.name }}"
      password: "{{ item.password | password_hash('sha512') }}"
      shell: /usr/sbin/nologin
      update_password: on_create
    loop: "{{ lookup('list', samba_users) }}"
  - name: Install samba
    apt:
      pkg:
        - samba
        - samba-common-bin
    become: true

  - name: Create folder for samba config
    file:
      path: "/etc/samba/"
      state: directory

  ## Configure snapraid
  - name: Copy samba configuration file
    copy:
      src: "../files/smb.conf"
      dest: "/etc/samba/smb.conf"
    become: true

  - name: Restart samba so it picks up changes
    ansible.builtin.systemd:
      state: restarted
      daemon_reload: yes
      name: smbd


